### ISSUE TITLE
UploadNft API using projectuid (string) on testnet

### ISSUE THREAD

**Issue by xryoshi** [3based/pix#5]
I'm tryin' to compile for testnet, but there's error caused by UploadNft API, because now using projectuid (string) parameter instead of nftprojectid (int).

https://api-testnet.nft-maker.io/swagger/index.html

![Screenshot 2022-03-13 204024](https://user-images.githubusercontent.com/2248792/158062253-7f257f39-50fb-4689-ba96-9ec92d9e4bcd.png)

**Comment by rvcas** [comment]
@xryoshi Thanks for filing an issue. I'm not sure if the best move is to wait for V2 to hit mainnet or not. We can definitely do something to fix it though. Maybe a param in the nft-maker config `network` that says testnet or mainnet. But also uploading your images doesn't mint them. So you can always test a few out and delete them from the project later.

**Comment by rvcas** [comment]
I think I'll go ahead and add support for a network parameter. Using that I can decide how to parse the projectid

**Comment by xryoshi** [comment]
that's a good solution, thanks @rvcas !

**Comment by rvcas** [comment]
@xryoshi let me know if the issue is fixed for you. in the config you can now do this. make sure to get the latest `main` and recompile the code.

```json
{
  "nft_maker_config": {
    "network": "testnet",
    "apikey": "XXX",
    "nft_project_id": "uid"
  }
}

**Comment by xryoshi** [comment]
Hi @rvcas,I just tried, and this issue is fixed, thankyou !
